- type: job
  id: Captain
  name: job-name-captain
  description: job-description-captain
  playTimeTracker: JobCaptain
  requirements:
    - !type:CharacterDepartmentTimeRequirement
      department: Logistics
      min: 3600 # 1 hour
    - !type:CharacterDepartmentTimeRequirement
      department: Engineering
      min: 3600 # 1 hour
    - !type:CharacterDepartmentTimeRequirement
      department: Medical
      min: 3600 # 1 hour
    - !type:CharacterDepartmentTimeRequirement
      department: Security
      min: 3600 # 1 hour
    - !type:CharacterDepartmentTimeRequirement
      department: Epistemics
      min: 3600 # 1 hour
    - !type:CharacterDepartmentTimeRequirement
      department: Command
      min: 10800 # 3 hours
    - !type:CharacterTraitRequirement
      inverted: true
      traits:
        - Foreigner
        - ForeignerLight
        - Pacifist
    # - !type:CharacterWhitelistRequirement # Undo Starch's blatant delete instead of commenting
  weight: 20
  startingGear: CaptainGear
  icon: "JobIconCaptain"
  requireAdminNotify: true
  joinNotifyCrew: true
  supervisors: job-supervisors-centcom
  canBeAntag: false
  accessGroups:
  - AllAccess
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff
  afterLoadoutSpecial:
  - !type:ModifyEnvirosuitSpecial
    charges: 8
  - !type:ModifyEnvirohelmSpecial
    powerCell: PowerCellHigh

- type: startingGear
  id: CaptainGear
  subGear:
  - CaptainPlasmamanGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitCaptain
    back: ClothingBackpackCaptainFilled
    shoes: ClothingShoesBootsLaceup
    id: CaptainPDA
    ears: ClothingHeadsetAltCommand
  innerClothingSkirt: ClothingUniformJumpskirtCaptain
  satchel: ClothingBackpackSatchelCaptainFilled
  duffelbag: ClothingBackpackDuffelCaptainFilled

- type: startingGear
  id: CaptainPlasmamanGear
  parent: BasePlasmamanGear
  equipment:
    jumpsuit: ClothingUniformEnvirosuitCaptain
    head: ClothingHeadEnvirohelmCaptain
    gloves: ClothingHandsGlovesCaptain
