- type: job
  id: BlueshieldOfficer
  name: 'офицер "синий щит"'
  description: "Выступайте в роли телохранителя и советника для командования и VIP-персон ЦентКома."
  playTimeTracker: JobBlueshieldOfficer
  requirements:
    - !type:CharacterDepartmentTimeRequirement
      department: Command
      min: 1800 # 30 minutes
    - !type:CharacterDepartmentTimeRequirement
      department: Medical
      min: 3600 # 1 hour
    - !type:CharacterDepartmentTimeRequirement
      department: Security
      min: 3600 # 1 hour
    - !type:CharacterTraitRequirement
      inverted: true
      traits:
        - Foreigner
        - ForeignerLight
        - Muted
        - Blindness
        - Pacifist
        - BrittleBoneDisease
  weight: 20
  startingGear: BlueshieldOfficerGear
  icon: "JobIconBlueshield"
  requireAdminNotify: true
  joinNotifyCrew: true
  supervisors: job-supervisors-centcom
  canBeAntag: false
  access:
  - Security
  - Brig
  - External
  - Cryogenics
  - Maintenance
  - Engineering
  - Medical
  - Research
  - Cargo
  - Command
  - CentralCommand
  - BlueshieldOfficer
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff
      - type: CPRTraining
  afterLoadoutSpecial:
  - !type:ModifyEnvirosuitSpecial
    charges: 8
  - !type:ModifyEnvirohelmSpecial
    powerCell: PowerCellHigh

- type: startingGear
  id: BlueshieldOfficerGear
  subGear:
  - BlueshieldPlasmamanGear
  equipment:
    back: ClothingBackpackBlueshield
    jumpsuit: ClothingUniformJumpsuitBlueshieldOfficer
    shoes: ClothingShoesBootsCombatFilled
    eyes: ClothingEyesGlassesMedSec
    ears: ClothingHeadsetCentCom
    gloves: ClothingHandsGlovesCombat
    id: BlueshieldPDA
    pocket1: UniqueBlueshieldOfficerLockerTeleporter

    #outerClothing: ClothingBlueshieldArmourVest
    #ears: ClothingHeadsetAltCommand
    #belt: ClothingBeltSecurityFilled
    #pocket1: WeaponPistolMk58
    #pocket2: DeathAcidifierImplanter

- type: startingGear
  id: BlueshieldPlasmamanGear
  parent: BasePlasmamanGear
  equipment:
    jumpsuit: ClothingUniformEnvirosuitBlueshield
    head: ClothingHeadEnvirohelmBlueshield
    gloves: ClothingHandsGlovesEnviroglovesBlack
